# fly.toml app configuration file generated for draftmancer on 2023-05-24T09:54:53+02:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "draftmancer"
primary_region = "dfw"
kill_signal = "SIGINT"
kill_timeout = "5s"

[build]
  [build.args]
    NODE_ENV = "production"

[deploy]
  strategy = "rolling"

[env]
  NODE_ENV = "production"
  NODE_OPTIONS = "--max-old-space-size=800"
  PORT = "8080"
  PERSISTENCE_LOCAL_PATH = "/persistence/"
  # SWAP = "true"

[mounts]
  source = "draftmancer_data"
  destination = "/persistence"

[experimental]
  auto_rollback = true

[[services]]
  protocol = "tcp"
  internal_port = 8080
  processes = ["app"]
  auto_stop_machines = false
  auto_start_machines = false

  [[services.ports]]
    port = 80
    handlers = ["http"]
    force_https = true

  [[services.ports]]
    port = 443
    handlers = ["tls", "http"]
  [services.concurrency]
    type = "connections"
    hard_limit = 1000
    soft_limit = 800

  [[services.tcp_checks]]
    interval = "15s"
    timeout = "2s"
    grace_period = "7s"
    restart_limit = 0
